---
title: "Anscombe's quartet"
author: "Hsu, Yao-Chih"
date: "2025-06-02"
output: html_notebook
---

# load datasets
```{r}
# dataset 1
x1 <- c(10.0, 8.0, 13.0, 9.0, 11.0, 14.0, 6.0, 4.0, 12.0, 7.0, 5.0)
y1 <- c(8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68)

# dataset 2
x2 <- c(10.0, 8.0, 13.0, 9.0, 11.0, 14.0, 6.0, 4.0, 12.0, 7.0, 5.0)
y2 <- c(9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74)

# dataset 3
x3 <- c(10.0, 8.0, 13.0, 9.0, 11.0, 14.0, 6.0, 4.0, 12.0, 7.0, 5.0)
y3 <- c(7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73)

# dataset 4
x4 <- c(8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 19.0, 8.0, 8.0, 8.0)
y4 <- c(6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89)

# collactions
x = cbind(x1, x2, x3, x4)
y = cbind(y1, y2, y3, y4)

# print
cat('x:\n')
print(x)

cat('y:\n')
print(y)
```

# means, variances, and correlation coefficients
```{r}
# means
cat('means:\n')
colMeans(x)
colMeans(y)

# variances
cat('variances:\n')
apply(x, 2, var)
apply(y, 2, var)

# correlation coefficients
cat('correlation coefficients:\n')
cor(x, y)
```

# linear regression
```{r}
# dataset 1
lm1 <- lm(y1 ~ x1)
summary(lm1)
```

```{r}
# dataset 2
lm2 <- lm(y2 ~ x2)
summary(lm2)
```

```{r}
# dataset 3
lm3 <- lm(y3 ~ x3)
summary(lm3)
```

```{r}
# dataset 4
lm4 <- lm(y4 ~ x4)
summary(lm4)
```
# coefficients matrix
```{r}
coefficients_matrix <- rbind(
  coef(lm1),
  coef(lm2),
  coef(lm3),
  coef(lm4)
)

rownames(coefficients_matrix) <- c("lm1", "lm2", "lm3", "lm4")
colnames(coefficients_matrix) <- c("Intercept", "Slope")

coefficients_matrix
```

# visualizations
```{r}
#png("anscombe_plot.png", width = 6, height = 6, units = "in", res = 300)
par(mfrow = c(2, 2))

plot(x1, y1, main = "Dataset 1", pch = 19)
abline(lm1, col = "red")

plot(x2, y2, main = "Dataset 2", pch = 19)
abline(lm2, col = "red")

plot(x3, y3, main = "Dataset 3", pch = 19)
abline(lm3, col = "red")

plot(x4, y4, main = "Dataset 4", pch = 19)
abline(lm4, col = "red")

#dev.off()
```






